services:
  db_backup:
    image: postgres:15
    container_name: odoo_db_backup
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5433:5432"
    volumes:
      - db_backup_data:/var/lib/postgresql/data

  odoo_backup:
    image: odoo:18
    container_name: odoo_backup
    depends_on:
      - db_backup
    ports:
      - "8070:8069"
    environment:
      HOST: db_backup
      USER: odoo
      PASSWORD: odoo
      # PORT: 5432   # opcional
    volumes:
      - ./extra-addons:/mnt/extra-addons

volumes:
  db_backup_data: